"""Live execution and test coverage analyzer using LCOV format."""
from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path
from typing import Callable


class CoverageTrace:
    """
    Compatibility wrapper for in-process coverage tracing.
    """

    def __init__(self, watch_dir: str):
        self.watch_dir = str(Path(watch_dir).resolve())
        self.executed_lines: dict[str, set[int]] = {}
        self._prev_trace: Callable | None = None

    def start(self) -> None:
        self._prev_trace = sys.gettrace()

    def stop(self) -> None:
        sys.settrace(self._prev_trace)


def parse_lcov(lcov_path: Path | str, repo_root: Path) -> dict[str, set[int]]:
    """
    Parse a standard LCOV coverage file into:
    relative_posix_path -> set of executed line numbers.
    """
    path = Path(lcov_path)
    if not path.is_file():
        return {}

    executed: dict[str, set[int]] = {}
    current_file: str | None = None

    try:
        content = path.read_text(encoding="utf-8", errors="ignore")
    except Exception:
        return {}

    for line in content.splitlines():
        line = line.strip()
        if line.startswith("SF:"):
            raw_path = line[3:].strip()
            p = Path(raw_path)
            if p.is_absolute():
                try:
                    current_file = p.relative_to(repo_root).as_posix()
                except ValueError:
                    current_file = p.as_posix()
            else:
                current_file = p.as_posix()
        elif line.startswith("DA:") and current_file:
            parts = line[3:].split(",")
            if len(parts) >= 2:
                try:
                    lineno = int(parts[0])
                    hits = int(parts[1])
                    if hits > 0:
                        executed.setdefault(current_file, set()).add(lineno)
                except ValueError:
                    pass
        elif line == "end_of_record":
            current_file = None

    return executed


def run_tests_with_trace(
    repo_path: str,
    test_command: list[str] | None = None,
) -> dict[str, set[int]]:
    """
    Run tests and collect executed lines via standard LCOV coverage format.
    Auto-detects test runners (npm/Jest, pytest, Go) and parses lcov.info.
    """
    repo = Path(repo_path).resolve()

    if test_command:
        cmd = test_command
    elif (repo / "package.json").exists():
        cmd = ["npm", "test", "--", "--coverage", "--coverageReporters=lcov"]
    elif (repo / "go.mod").exists():
        cmd = ["go", "test", "-coverprofile=coverage.out", "./..."]
    else:
        cmd = ["python", "-m", "pytest", "--cov=.", "--cov-report=lcov", "--tb=no", "-q"]

    try:
        subprocess.run(
            cmd,
            cwd=str(repo),
            capture_output=True,
            timeout=180,
            shell=(sys.platform == "win32" and cmd[0] == "npm"),
        )
    except Exception:
        pass

    lcov_candidates = [
        repo / "coverage" / "lcov.info",
        repo / "lcov.info",
        repo / "coverage.lcov",
        repo / ".coverage.lcov",
    ]

    for candidate in lcov_candidates:
        if candidate.is_file():
            res = parse_lcov(candidate, repo)
            if res:
                return res

    return {}


def check_coverage_gaps(
    executed: dict[str, set[int]],
    changed_files: list[str],
    claim: str,
) -> list[str]:
    """
    Cross-reference executed lines against changed files across all languages.
    Returns a list of human-readable flag strings.
    """
    flags: list[str] = []
    if not executed:
        flags.append("Notice: No LCOV coverage report was generated by the test runner.")
        return flags

    for rel_path in changed_files:
        posix_path = Path(rel_path).as_posix()
        if posix_path not in executed:
            flags.append(f"{posix_path}: changed but never executed during test run")
        else:
            flags.append(f"{posix_path}: executed {len(executed[posix_path])} line(s) under trace")
    return flags

